"use client";

/**
 * GUIDES tab — the operator documentation, served from inside the app.
 *
 * The guides are rendered in an <iframe> rather than converted to React, and
 * that is deliberate. There is exactly one copy of the prose, in
 * docs/guides/*.html; `scripts/build_guides.py` wraps it into the standalone
 * pages under public/guides/ that this panel loads, and the same fragment is
 * what gets published as the shareable web version. Re-authoring the content
 * as components would create a second copy to keep in sync, and this project
 * has already been bitten several times by documentation drifting from what
 * it describes.
 *
 * The iframe is same-origin, so it inherits nothing and leaks nothing, and the
 * generated pages carry `data-theme="dark"` so they match the workspace
 * instead of following the viewer's OS preference.
 */

import { useEffect, useRef, useState } from "react";

interface Guide {
  id: string;
  /** Short label for the switcher. */
  label: string;
  /** One line: who it's for and what it answers. */
  blurb: string;
  /** Served from public/guides/, generated by scripts/build_guides.py. */
  file: string;
}

const GUIDES: Guide[] = [
  {
    id: "enhance",
    label: "The Enhance Tab",
    blurb:
      "Every control in the order you use it, how to write a prompt that works, and how to read the quality check.",
    file: "/guides/enhance-tab.html",
  },
  {
    id: "templates",
    label: "Prompt Templates",
    blurb:
      "The shared template library — using one, saving one, shortening a long one, and the rules that can't be undone.",
    file: "/guides/prompt-templates.html",
  },
];

export function GuidesPanel() {
  const [activeId, setActiveId] = useState(GUIDES[0].id);
  const frameRef = useRef<HTMLIFrameElement>(null);

  const active = GUIDES.find((g) => g.id === activeId) ?? GUIDES[0];

  // Belt and braces on the theme. The generated pages already ship
  // data-theme="dark", but if someone serves an un-regenerated fragment the
  // page would follow the OS preference and render light inside a dark app.
  // Same-origin, so reaching into contentDocument is allowed; wrapped anyway
  // because a cross-origin or not-yet-loaded frame throws.
  useEffect(() => {
    const frame = frameRef.current;
    if (!frame) return;
    const pin = () => {
      try {
        const doc = frame.contentDocument;
        if (doc?.documentElement) doc.documentElement.dataset.theme = "dark";
      } catch {
        /* cross-origin or not ready — the page's own default covers it */
      }
    };
    frame.addEventListener("load", pin);
    pin();
    return () => frame.removeEventListener("load", pin);
  }, [activeId]);

  return (
    <section className="space-y-4">
      <div className="rounded-xl border border-line bg-well/60 overflow-hidden">
        <div className="px-5 py-4 space-y-3">
          <div className="flex items-baseline justify-between gap-3 flex-wrap">
            <h2 className="text-base font-semibold uppercase tracking-[0.14em] text-ink">
              Guides
            </h2>
            <a
              href={active.file}
              target="_blank"
              rel="noreferrer"
              className="text-sm font-bold text-accent hover:underline"
            >
              Open in a new tab ↗
            </a>
          </div>

          {/* Two guides today, so a row of buttons beats a sidebar. If this
              grows past ~5, move it to a left rail. */}
          <div className="flex flex-wrap gap-2" role="tablist" aria-label="Guides">
            {GUIDES.map((g) => {
              const isActive = g.id === activeId;
              return (
                <button
                  key={g.id}
                  type="button"
                  role="tab"
                  aria-selected={isActive}
                  onClick={() => setActiveId(g.id)}
                  className={`text-sm uppercase tracking-[0.14em] font-bold px-4 py-2.5 rounded-lg border-2 transition-colors ${
                    isActive
                      ? "border-accent bg-accent text-header-bg"
                      : "border-line bg-panel text-ink hover:bg-panel-hi"
                  }`}
                >
                  {g.label}
                </button>
              );
            })}
          </div>

          <p className="text-sm text-ink-soft leading-relaxed max-w-3xl">
            {active.blurb}
          </p>
        </div>

        <div className="border-t border-line">
          <iframe
            ref={frameRef}
            key={active.id}
            src={active.file}
            title={active.label}
            className="w-full block bg-bg"
            style={{ height: "calc(100vh - 20rem)", minHeight: "34rem" }}
          />
        </div>
      </div>

      <p className="text-sm text-ink-soft leading-relaxed">
        Something here wrong or out of date?{" "}
        <strong className="text-ink">Say so</strong> — these are written against
        the code, and when the code changes ahead of them they become worse than
        nothing.
      </p>
    </section>
  );
}
