"""
Gemini Service
Wraps google-genai client for condition enhancement processing.
"""

import structlog
from typing import Optional, List
from google import genai
from tenacity import retry, stop_after_attempt, wait_exponential_jitter

from app.config import settings


logger = structlog.get_logger()


class GeminiService:
    """Service for Gemini 2.5 Flash Image operations."""
    
    def __init__(self, client: genai.Client, storage_service):
        self.client = client
        self.storage_service = storage_service
        self.model = settings.gemini_model
        
    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential_jitter(initial=1, max=30),
        reraise=True
    )
    async def enhance_forklift_condition(
        self, 
        image_gcs_uri: str,
        enhancement_level: str = "moderate",
        reference_images: Optional[List[str]] = None
    ) -> str:
        """
        Apply condition enhancement to a forklift image using Gemini 2.5 Flash Image.
        
        Args:
            image_gcs_uri: GCS URI of the image to enhance
            enhancement_level: "light", "moderate", or "heavy" 
            reference_images: Optional list of reference image URIs for subject consistency
            
        Returns:
            GCS URI of the enhanced image
        """
        logger.info("Starting condition enhancement",
                    image_uri=image_gcs_uri,
                    level=enhancement_level)
        
        # Build the prompt based on enhancement level
        prompts = {
            "light": (
                "Enhance this forklift to look clean and well-maintained. "
                "Remove surface dust, dirt, and minor scuffs. "
                "The forklift should appear professionally cleaned. "
                "Preserve the exact color, decals, data plate, and proportions. "
                "Match perspective and lighting of the original."
            ),
            "moderate": (
                "Restore this forklift to good working condition appearance. "
                "Remove rust, dirt, scratches, and minor dents. "
                "The paint should look fresh but not necessarily new. "
                "Clean all surfaces and components. "
                "Preserve the exact color, decals, data plate, and proportions. "
                "Match perspective and lighting of the original."
            ),
            "heavy": (
                "Restore this forklift to like-new condition. "
                "The paint is fresh, all surfaces are pristine, "
                "no rust, corrosion, dirt, scratches, chipped paint, or wear. "
                "All components should appear new and properly maintained. "
                "Preserve the exact color, decals, data plate, and proportions. "
                "Match perspective and lighting of the original."
            )
        }
        
        prompt = prompts.get(enhancement_level, prompts["moderate"])
        
        # Build content parts for the request
        content_parts = []
        
        # Add the main image
        content_parts.append({
            "fileData": {
                "fileUri": image_gcs_uri,
                "mimeType": "image/jpeg"
            }
        })
        
        # Add reference images if provided
        if reference_images:
            for ref_uri in reference_images[:2]:  # Limit to 2 references for cost control
                content_parts.append({
                    "fileData": {
                        "fileUri": ref_uri,
                        "mimeType": "image/jpeg"
                    }
                })
        
        # Add the text prompt
        content_parts.append({"text": prompt})
        
        try:
            # Call Gemini 2.5 Flash Image
            response = await self.client.aio.models.generate_content(
                model=self.model,
                contents=[{
                    "role": "user",
                    "parts": content_parts
                }],
                config=genai.GenerationConfig(
                    response_modalities=["IMAGE"],
                    temperature=0.3,  # Lower temperature for consistency
                    max_output_tokens=1  # We only want the image, not text
                )
            )
            
            if not response.candidates or not response.candidates[0].content.parts:
                raise ValueError("No image generated by Gemini")
                
            # Extract the generated image
            image_part = response.candidates[0].content.parts[0]
            if not hasattr(image_part, 'inline_data'):
                raise ValueError("Generated content is not an image")
                
            # Save the enhanced image to GCS
            enhanced_uri = await self.storage_service.save_enhanced_image(
                image_data=image_part.inline_data.data,
                original_uri=image_gcs_uri,
                enhancement_level=enhancement_level
            )
            
            logger.info("Condition enhancement completed",
                        original_uri=image_gcs_uri,
                        enhanced_uri=enhanced_uri,
                        level=enhancement_level)
            
            return enhanced_uri
            
        except Exception as e:
            logger.error("Condition enhancement failed",
                        image_uri=image_gcs_uri,
                        error=str(e))
            raise
