"""
Wrap the canonical guide fragments into standalone pages for the GUIDES tab.

    python scripts/build_guides.py

SOURCE OF TRUTH is docs/guides/*.html. Those are FRAGMENTS — no <!doctype>,
no <html>, no <head>, no <body> — because that is the form the Artifact
publisher requires (it supplies the document skeleton itself). Editing the
generated files in apps/web/public/guides/ is pointless; this script
overwrites them.

So there is exactly one copy of the prose, and two renderings of it:

    docs/guides/*.html   ──┬──►  published Artifact (fragment, as-is)
                           └──►  apps/web/public/guides/*.html (this script)

The generated copy differs in three ways, all of them mechanical:

  1. It gets a real document wrapper with charset and viewport.
  2. It is pinned to the dark theme. The fragments are theme-adaptive for the
     shared web version; inside the app, which is dark-only, a light page in
     an iframe looks broken.
  3. Cross-links between the guides are rewritten from their claude.ai
     artifact URLs to local paths, so clicking one inside the app doesn't
     navigate the iframe out to the web.

No external dependencies.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SRC_DIR = Path("docs/guides")
OUT_DIR = Path("apps/web/public/guides")
TS_OUT = Path("apps/web/components/guides/guide-html.generated.ts")

# Published artifact URL -> local path, applied to the in-app copies only.
CROSS_LINKS = {
    "https://claude.ai/code/artifact/10f72d91-60b2-4968-9e1e-1fa9084a189e":
        "/guides/enhance-tab.html",
    "https://claude.ai/code/artifact/11ae4d13-64b2-4894-b488-0ceccb4211c5":
        "/guides/prompt-templates.html",
}

# Matches the fragment's own <title>, which the wrapper hoists into <head>.
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S | re.I)

SHELL = """<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<!-- GENERATED by scripts/build_guides.py from docs/guides/{src}.
     Do not edit this file. Edit the source and re-run the script. -->
<style>
  /* The app is dark-only, so pin the page rather than letting it follow the
     viewer's OS preference — a light guide inside a dark workspace reads as a
     rendering fault. `data-theme="dark"` on <html> is the hook the fragment's
     own token block already honours. */
  html, body {{ margin: 0; padding: 0; }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def build() -> int:
    if not SRC_DIR.is_dir():
        print(f"error: {SRC_DIR} not found — run from the repo root", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    entries: list[tuple[str, str, str]] = []
    sources = sorted(SRC_DIR.glob("*.html"))
    if not sources:
        print(f"error: no fragments in {SRC_DIR}", file=sys.stderr)
        return 1

    for src in sources:
        fragment = src.read_text(encoding="utf-8")

        m = TITLE_RE.search(fragment)
        if m is None:
            print(f"error: {src} has no <title>", file=sys.stderr)
            return 1
        title = m.group(1).strip()

        # The wrapper owns the <title>; leaving the fragment's copy in <body>
        # is invalid and some browsers render it as text.
        body = TITLE_RE.sub("", fragment, count=1).lstrip("\n")

        for url, local in CROSS_LINKS.items():
            body = body.replace(url, local)

        out = OUT_DIR / src.name
        out.write_text(
            SHELL.format(title=title, src=src.name, body=body),
            encoding="utf-8",
        )
        print(f"wrote {out} ({out.stat().st_size:,} bytes) — {title}")

        entries.append((src.stem, title, _shadow_ready(body)))

    _write_ts(entries)
    return 0


def _shadow_ready(body: str) -> str:
    """Rewrite the fragment so it works inside a shadow root.

    `:root` does NOT match inside a shadow tree — it matches the document root,
    which the shadow tree cannot see. Left alone, every custom property in the
    guide's token block would be undefined and the page would render as
    unstyled black-on-transparent text. `:host` is the shadow-tree equivalent.

    Order matters. The specific selectors are rewritten first, because
    replacing bare `:root` first would corrupt them into `:host[data-theme=...]`
    which matches nothing.

    The three token blocks become, in source order: light, dark-under-media,
    dark-unconditional. The last one always applies and always wins, which is
    what pins the guide to the app's dark theme.
    """
    body = body.replace(':root[data-theme="dark"]', ":host")
    body = body.replace(':root:not([data-theme="light"])', ":host")
    body = body.replace(":root", ":host")
    # `body { … }` can't match inside a shadow tree either. That rule only set a
    # background and margin, both of which `.page` sets for itself, so it can
    # stay dead — but :host needs a box of its own or the panel collapses.
    #
    # Must be inside a <style> element. A bare rule pasted ahead of the markup
    # is just text, and renders as a literal "…display:block" at the top of the
    # guide.
    return "<style>:host{display:block}</style>\n" + body


def _ts_literal(s: str) -> str:
    """Escape for a TypeScript backtick template literal."""
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def _write_ts(entries: list[tuple[str, str, str]]) -> None:
    """Emit the guides as importable strings.

    Inlined into the bundle rather than fetched. A fetch or an iframe can be
    intercepted by the auth proxy, blocked by a response header, or answered
    with a login page — all three of which are invisible failures that render
    as a blank rectangle. A string import cannot fail.

    The chunk is only downloaded when the GUIDES tab is opened (the panel is
    dynamically imported), so this costs nothing on first paint.
    """
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "// GENERATED by scripts/build_guides.py from docs/guides/*.html.",
        "// Do not edit. Edit the source fragments and re-run the script.",
        "//",
        "// `:root` has been rewritten to `:host` so the token blocks resolve",
        "// inside a shadow root — see _shadow_ready() in the script.",
        "",
        "export interface GuideHtml {",
        "  id: string;",
        "  title: string;",
        "  html: string;",
        "}",
        "",
        "export const GUIDE_HTML: GuideHtml[] = [",
    ]
    for stem, title, html in entries:
        parts.append("  {")
        parts.append(f"    id: {stem!r}".replace("'", '"') + ",")
        parts.append(f"    title: {title!r}".replace("'", '"') + ",")
        parts.append("    html: `" + _ts_literal(html) + "`,")
        parts.append("  },")
    parts.append("];")
    parts.append("")
    TS_OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {TS_OUT} ({TS_OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    raise SystemExit(build())
