"""
Wrap the canonical guide fragments into standalone pages for the GUIDES tab.

    python scripts/build_guides.py

SOURCE OF TRUTH is docs/guides/*.html. Those are FRAGMENTS — no <!doctype>,
no <html>, no <head>, no <body> — because that is the form the Artifact
publisher requires (it supplies the document skeleton itself). Editing the
generated files in apps/web/public/guides/ is pointless; this script
overwrites them.

So there is exactly one copy of the prose, and two renderings of it:

    docs/guides/*.html   ──┬──►  published Artifact (fragment, as-is)
                           └──►  apps/web/public/guides/*.html (this script)

The generated copy differs in three ways, all of them mechanical:

  1. It gets a real document wrapper with charset and viewport.
  2. It is pinned to the dark theme. The fragments are theme-adaptive for the
     shared web version; inside the app, which is dark-only, a light page in
     an iframe looks broken.
  3. Cross-links between the guides are rewritten from their claude.ai
     artifact URLs to local paths, so clicking one inside the app doesn't
     navigate the iframe out to the web.

No external dependencies.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SRC_DIR = Path("docs/guides")
OUT_DIR = Path("apps/web/public/guides")

# Published artifact URL -> local path, applied to the in-app copies only.
CROSS_LINKS = {
    "https://claude.ai/code/artifact/10f72d91-60b2-4968-9e1e-1fa9084a189e":
        "/guides/enhance-tab.html",
    "https://claude.ai/code/artifact/11ae4d13-64b2-4894-b488-0ceccb4211c5":
        "/guides/prompt-templates.html",
}

# Matches the fragment's own <title>, which the wrapper hoists into <head>.
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S | re.I)

SHELL = """<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<!-- GENERATED by scripts/build_guides.py from docs/guides/{src}.
     Do not edit this file. Edit the source and re-run the script. -->
<style>
  /* The app is dark-only, so pin the page rather than letting it follow the
     viewer's OS preference — a light guide inside a dark workspace reads as a
     rendering fault. `data-theme="dark"` on <html> is the hook the fragment's
     own token block already honours. */
  html, body {{ margin: 0; padding: 0; }}
</style>
</head>
<body>
{body}
</body>
</html>
"""


def build() -> int:
    if not SRC_DIR.is_dir():
        print(f"error: {SRC_DIR} not found — run from the repo root", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    sources = sorted(SRC_DIR.glob("*.html"))
    if not sources:
        print(f"error: no fragments in {SRC_DIR}", file=sys.stderr)
        return 1

    for src in sources:
        fragment = src.read_text(encoding="utf-8")

        m = TITLE_RE.search(fragment)
        if m is None:
            print(f"error: {src} has no <title>", file=sys.stderr)
            return 1
        title = m.group(1).strip()

        # The wrapper owns the <title>; leaving the fragment's copy in <body>
        # is invalid and some browsers render it as text.
        body = TITLE_RE.sub("", fragment, count=1).lstrip("\n")

        for url, local in CROSS_LINKS.items():
            body = body.replace(url, local)

        out = OUT_DIR / src.name
        out.write_text(
            SHELL.format(title=title, src=src.name, body=body),
            encoding="utf-8",
        )
        print(f"wrote {out} ({out.stat().st_size:,} bytes) — {title}")

    return 0


if __name__ == "__main__":
    raise SystemExit(build())
